manifest:
  remotes:
    - name: benvallack
      url-base: https://github.com/benvallack
  projects:
    - name: zmk-mouse-macro-dongle
      remote: benvallack
      revision: macro-dongle-mouse
      import: app/west.yml
  self:
    path: config
